export default {
  SPLASH_SCREEN: "SPLASH_SCREEN",
  HOME_SCREEN: "HOME_SCREEN",
  LOGIN_SCREEN: "LOGIN_SCREEN",
  WALLET_SCREEN: "WALLET_SCREEN",
  ADD_TOKEN_SCREEN: "ADD_TOKEN_SCREEN",
  ADD_POSITION_SCREEN: "ADD_POSITION_SCREEN",
};
